# Generated by Django 3.2.5 on 2021-07-17 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210717_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='full_name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerytype',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerytype',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='gallerytype',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='text_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='laboratory',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='body_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_en',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_ru',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='short_description_uz',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uz',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='about_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='about_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='about_uz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='name_uz',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
