# Generated by Django 3.2.5 on 2022-02-01 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210801_1300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
