# Generated by Django 3.2.5 on 2022-02-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_news_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='employee',
            name='telegram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='time_to_apply',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employee',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
