# Generated by Django 3.2.5 on 2022-02-07 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20220202_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
